networks:
  docker_services:
    external: true

services:
  postgres:
    container_name: postgres_db
    restart: always
    image: postgres:16.1-bullseye
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./backups:/backups
      - ./volumes/postgres/postgresql.conf:/volumes/postgres/postgresql.conf
    command: postgres -c 'config_file=/volumes/postgres/postgresql.conf'
    networks:
      - docker_services
    env_file:
      - .env
    ports:
      - 5432:5432
    shm_size: 1gb
    mem_limit: 2GB

  mysql:
    container_name: mysql_db
    restart: always
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - docker_services
    env_file:
      - .env
    ports:
      - 3306:3306
